### ISSUE TITLE
Графика

### ISSUE THREAD

**Issue by konovalovatanya26** [konovalovatanya26/prog_Konovalova#10]
@antosha417,  все создано в функциях и циклах, https://github.com/konovalovatanya26/prog_Konovalova/commit/e9ce22fa716b7c1391773d9e9f66a945f5cb06cd#diff-a9877a58b5b3280efb722dbd5ba99f36

**Comment by antosha417** [comment]
Если хочешь что-то сделать 10 раз, не выделяй на это имя переменной её обычно называют `_` это показывает, что она не учавствует в цикле, вот, например:
```python
for _ in range(10):
   print("Hello World!")
```
Однобуквенные переменные почти всегда плохо,

**Comment by antosha417** [comment]
Пока ставлю тебе 0,9  за задачу, чтобы поднять поправь код.

**Comment by konovalovatanya26** [comment]
@antosha417, исправила код, изменила цикл с облаками, https://github.com/konovalovatanya26/prog_Konovalova/commit/8af9e147f035678b245c33d50c327b016eaef538#diff-a9877a58b5b3280efb722dbd5ba99f36

**Comment by antosha417** [comment]
Закрывай
