### ISSUE TITLE
Черепашка

### ISSUE THREAD

**Issue by konovalovatanya26** [konovalovatanya26/prog_Konovalova#11]
@antosha417, задания по черепашке, https://github.com/konovalovatanya26/prog_Konovalova/commit/db50392e10e91f1c1b279eac5548cfd42b73b2b4#diff-be55907d5084330cc02e4a358db21d32

**Comment by antosha417** [comment]
Пайчарм ругается на твой кодстайл и несоблюдение пеп8, поправь, пожалуйста.

**Comment by antosha417** [comment]
Не нашёл фракталы, где они у тебя?

**Comment by antosha417** [comment]
Пока ставлю тебе 0,6 за задачу, чтобы поднять поправь код.

**Comment by konovalovatanya26** [comment]
antosha417, добавила фракталы, поправила РЕР 8, https://github.com/konovalovatanya26/prog_Konovalova/commit/d024b3842af68effd0a77ee7d2ec2b1f0db501de#diff-be55907d5084330cc02e4a358db21d32

**Comment by antosha417** [comment]
молодец, закрывай.
