### ISSUE TITLE
Поймай шарик

### ISSUE THREAD

**Issue by konovalovatanya26** [konovalovatanya26/prog_Konovalova#13]
@antosha417, добавила цвета, учитываются промахи, https://github.com/konovalovatanya26/prog_Konovalova/commit/185dec9012a7c0fadc6cfbc413475ccf9f1a2e6d#diff-67f3e17385c264d9e50f153c546a0add

**Comment by antosha417** [comment]
Замечательно, хочу чтобы за 1 шарик я мог потерять или заработать только 1 очко. То есть не мог кучу раз кликать и получить много очков.

**Comment by antosha417** [comment]
Пока ставлю тебе 07  за задачу, чтобы поднять поправь код.

**Comment by konovalovatanya26** [comment]
@antosha417, за один шарик можно заработать только одно очко, 
https://github.com/konovalovatanya26/prog_Konovalova/commit/496696e7f0971b8e12dc93b8927b883ee75b619b#diff-67f3e17385c264d9e50f153c546a0add

**Comment by konovalovatanya26** [comment]
@antosha417, исправила https://github.com/konovalovatanya26/prog_Konovalova/commit/496696e7f0971b8e12dc93b8927b883ee75b619b#diff-67f3e17385c264d9e50f153c546a0add

**Comment by antosha417** [comment]
Хорошо, вынеси создания окна и запуск игры в отдельную функцию и закрывай issue.
