### ISSUE TITLE
Однобуквенные переменные ЗЛО

### ISSUE THREAD

**Issue by antosha417** [konovalovatanya26/prog_Konovalova#2]
https://github.com/konovalovatanya26/prog_Konovalova/blob/848ea7497deb54ee26ce2dff997b70c67cc3b272/turtle/%D1%83%D0%BF%D1%80%2010.py#L4-L5
+ по PEP8 надо писать  с пробелами `x = 123`

**Comment by konovalovatanya26** [comment]
переименовала переменные

**Comment by antosha417** [comment]
Наверное, ты забыла запушить. 
![latest-screenshot](https://user-images.githubusercontent.com/14187674/47526064-61fe6480-d8a7-11e8-830e-2e7ce013d2b5.png)

**Comment by konovalovatanya26** [comment]
Переименовала переменные 2dcf5629b21670502c08c78d10a25790705440eb
