### ISSUE TITLE
Это 2 разных икса?

### ISSUE THREAD

**Issue by antosha417** [konovalovatanya26/prog_Konovalova#3]
https://github.com/konovalovatanya26/prog_Konovalova/blob/848ea7497deb54ee26ce2dff997b70c67cc3b272/turtle/%D1%83%D0%BF%D1%80%205.py#L5-L9
Странная конструкция со вложенным циклом и одной и той-же переменной `x`. Чему он, например, будет равен на 10-ой строчке? Лучше использовать разные имена, а если не используешь нигде, то называй `_`

**Comment by antosha417** [comment]
https://stackoverflow.com/questions/5893163/what-is-the-purpose-of-the-single-underscore-variable-in-python

**Comment by konovalovatanya26** [comment]
изменила название переменной

**Comment by antosha417** [comment]
Файл остался без изменений
