### ISSUE TITLE
[Поймай шарик] Сделай больше цветов

### ISSUE THREAD

**Issue by antosha417** [konovalovatanya26/prog_Konovalova#6]
https://github.com/konovalovatanya26/prog_Konovalova/blob/2c095ffcc162f4a5672bbd27c294d4f65153d565/tKinter.%20%D1%88%D0%B0%D1%80%D0%B8%D0%BA.py#L4
Вам не просто так рассказали про RGB

**Comment by konovalovatanya26** [comment]
antosha417 , добавила цвета, учитываются промахи, https://github.com/konovalovatanya26/prog_Konovalova/commit/185dec9012a7c0fadc6cfbc413475ccf9f1a2e6d#diff-67f3e17385c264d9e50f153c546a0add

**Comment by antosha417** [comment]
Теперь сдаём задачу в отдельном issue, этот закрываю
